# Generated by Django 4.2 on 2023-05-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=150, verbose_name='evento')),
                ('tematica', models.CharField(max_length=150, verbose_name='tematica ')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion')),
                ('Fevento', models.DateField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exponente', to='profesores.profesores')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
