# Generated by Django 4.2 on 2023-07-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregas',
            old_name='puntaje',
            new_name='calificacion',
        ),
    ]
