# Generated by Django 4.2 on 2023-07-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_rename_puntaje_entregas_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
