# Generated by Django 4.2 on 2023-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_alter_entregas_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='mensaje',
            field=models.CharField(max_length=255),
        ),
    ]
